config:
  name: __MSNAME__-config
  data:
    VARIABLE1: value1
    VARIABLE2: 'value2'

secret:
  name: __MSNAME__-secret
  data:
    # Values must be encoded as base64 (for example: echo -n 'SOME_SECRET' | base64)
    DDBB_USER: #{DDBB_USER}#
    DDBB_PASS: #{DDBB_PASS}#

customValues:
  namespace: 'test-namespace'
  replicas: '1'

  livenessPath: '/health'
  livenessProbe:
    httpGet.path: '/liveness-get-path'
    initialDelaySeconds: '60'
    periodSeconds: '10'
    timeoutSeconds: '10'
    failureThreshold: '3'

  readinessPath: '/readiness'
  readinessProbe:
    httpGet.path: '/readiness-get-path'
    initialDelaySeconds: '20'
    periodSeconds: '5'
    timeoutSeconds: '10'
    failureThreshold: '3'

  resources:
    requests:
      cpu: '100m'
      memory: '100Mi'
    limits:
      cpu: '200m'
      memory: '300Mi'
  
  ingress:
    enabled: true
    annotations:
      healthcheckPath: '/health'
    spec:
      httpPaths: '/api/test*'  